import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'

// Globals available in Node / server code.
const nodeGlobals = {
  process: 'readonly',
  console: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  Headers: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  fetch: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
}

// Globals available in the browser. Client components need these.
const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  indexedDB: 'readonly',
  IDBDatabase: 'readonly',
  IDBObjectStore: 'readonly',
  IDBRequest: 'readonly',
  IDBTransactionMode: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  EventTarget: 'readonly',
  DOMException: 'readonly',
  MutationObserver: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  matchMedia: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLDivElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLTableElement: 'readonly',
  HTMLSpanElement: 'readonly',
  HTMLParagraphElement: 'readonly',
  HTMLHeadingElement: 'readonly',
  HTMLLabelElement: 'readonly',
  HTMLUListElement: 'readonly',
  HTMLLIElement: 'readonly',
  SVGSVGElement: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  PointerEvent: 'readonly',
  TouchEvent: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  Image: 'readonly',
  ServiceWorkerRegistration: 'readonly',
  GeolocationPosition: 'readonly',
  GeolocationPositionError: 'readonly',
  ReadableStream: 'readonly',
}

export default [
  {
    // Nothing below this line should ever look at these.
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'next-env.d.ts',
      // Plain browser script, not part of the module graph. Has its own header.
      'public/sw.js',
      // Generated by drizzle-kit. Not hand-written, not our style.
      'supabase/**',
      'drizzle/**',
      '**/migrations/**',
      '**/*.sql',
    ],
  },

  js.configs.recommended,

  {
    // The whole project — server code, client components, tests, config.
    // Previously this was `app/**/*.ts` + `lib/**/*.ts`, which linted zero .tsx
    // files. All 65 UI files were unchecked, which is how a stale-closure bug in
    // the collection form reached production.
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: { ...nodeGlobals, ...browserGlobals },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...tseslint.configs['recommended'].rules,

      // Hooks. `rules-of-hooks` catches conditional hooks; `exhaustive-deps`
      // catches the stale-closure class of bug.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // Accessibility. This app is used one-handed, outdoors, in sunlight, by
      // non-technical users. Labels and roles are not optional here.
      ...jsxA11y.flatConfigs.recommended.rules,

      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-console': 'warn',
      // Turn off base rules — the TS versions handle them.
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'no-redeclare': 'off',
    },
  },

  {
    // Service modules use an intentional AnyDB pattern (accepts both db and tx).
    // Suppressing no-explicit-any here; the pattern is documented in each file.
    files: ['lib/modules/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    // Route files use `as any` casts because Drizzle's `conditions` array type
    // inference degrades when mixing eq/gte/lte/isNull results.
    // Validation files use `as any` for Zod v3/v4 cross-compat error access.
    // Tests build partial fixtures and poke at internals; `any` there is a
    // deliberate shortcut, not a type hole in shipped code.
    files: ['app/api/**/*.ts', 'lib/validation/**/*.ts', '__tests__/**/*.ts', 'tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    // Error utilities and authorize helper intentionally log to console server-side.
    // Server-side error logging is intentional in route handlers and service
    // helpers — it is the only record when a request fails in production.
    files: ['lib/utils/error.ts', 'lib/auth/authorize.ts', 'app/api/**/*.ts', 'lib/modules/**/*.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },

  {
    // Tests assert on loosely-typed mocks and print diagnostics.
    files: ['__tests__/**/*.ts', 'scripts/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      'no-console': 'off',
    },
  },

  // =========================================================================
  // HANDOFF OVERRIDES — TEMPORARY. Delete each entry as it is fixed.
  //
  // These are real violations in files owned by other agents on this branch.
  // The infrastructure agent that turned linting on for .tsx (and raised the
  // bar to --max-warnings 0) must not edit those files, so each violation is
  // scoped to the exact file and the exact rule, and listed in the handoff
  // notes. Nothing here is a blanket disable.
  // =========================================================================

  {
    // ROOT CAUSE: next-auth's `Session['user']` is not augmented with this
    // app's claims (role / branch_id / employee_code), so every server page
    // reads them via `session.user as any`.
    // FIX: add a `declare module 'next-auth'` augmentation, then delete this.
    files: [
      'app/(dashboard)/**/*.tsx',
      'lib/auth.ts',
      'lib/auth/authorize.ts',
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    // Recharts types its `formatter` / `labelFormatter` callbacks loosely, and
    // these two files map untyped JSON rows straight from fetch().
    // FIX: type the fetch responses via lib/api-client.ts generics.
    files: [
      'components/dashboard-client.tsx',
      'components/reconciliation/admin-reconciliation-client.tsx',
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    // Dead imports and dead locals left behind by in-flight refactors.
    // FIX: delete the unused symbol. Then delete this block.
    files: [
      'app/(dashboard)/expenses/page.tsx',
      'app/(dashboard)/profile/profile-client.tsx',
      // `*` not `[id]` — square brackets are a character class in a glob.
      'app/(dashboard)/customers/*/page.tsx',
      'components/attendance/admin-attendance-client.tsx',
      'components/attendance/attendance-client.tsx',
      'components/collections/collection-form.tsx',
      'components/dashboard-client.tsx',
      'components/dashboard/dashboard-client.tsx',
      'components/employees/employee-table.tsx',
      'components/notification-bell.tsx',
    ],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },

  {
    // components/notification-bell.tsx has an empty catch block (swallows the
    // error silently) and a <div onClick> with no keyboard path — unreachable
    // for anyone not using touch or a mouse.
    // FIX: log or handle in the catch; make the div a <button>.
    files: ['components/notification-bell.tsx'],
    rules: {
      'no-empty': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
    },
  },

  {
    // <Label> renders a bare <label> with no htmlFor and no nested control.
    // FIX: require `htmlFor`, or render through <FormField>.
    files: ['components/ui/label.tsx'],
    rules: {
      'jsx-a11y/label-has-associated-control': 'off',
    },
  },

  {
    // autoFocus steals focus and fires the on-screen keyboard on a phone.
    // FIX: focus() in an effect only when the user opened the panel.
    files: ['components/collections/admin-collections-client.tsx'],
    rules: {
      'jsx-a11y/no-autofocus': 'off',
    },
  },

  {
    // A lazy `require()` inside a seed script, to avoid a top-level import.
    // FIX: use a dynamic `await import()`.
    files: ['scripts/seed-users.ts'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    // Config files run in Node with CommonJS-ish globals.
    files: ['*.config.{ts,mts,js,mjs}', 'drizzle.config.ts'],
    languageOptions: { globals: nodeGlobals },
    rules: {
      'no-console': 'off',
    },
  },
]
