'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Plus } from 'lucide-react'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
import { FormField } from '@/components/ui/form-field'
import { ActionButton } from '@/components/ui/action-button'
import { Bi } from '@/components/ui/bi'
import { apiPost } from '@/lib/api-client'
import { toNumber } from '@/lib/format'
import { t } from '@/lib/i18n'

interface FormState {
  invoice_number: string
  reference: string
  amount: string
  due_date: string
  notes: string
  penalty_rate: string
}

const emptyForm: FormState = {
  invoice_number: '',
  reference: '',
  amount: '',
  due_date: '',
  notes: '',
  penalty_rate: '0',
}

interface DueResponse {
  id: string
}

export function AddDueDialog({ customerId }: { customerId: string }) {
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<FormState>(emptyForm)
  const [saving, setSaving] = useState(false)
  const [err, setErr] = useState<string | null>(null)

  function field<K extends keyof FormState>(key: K, val: string) {
    setForm(f => ({ ...f, [key]: val }))
  }

  async function save() {
    if (!form.amount || toNumber(form.amount) <= 0) {
      setErr(t('amountMustBePositive').en)
      return
    }
    setSaving(true)
    setErr(null)

    const res = await apiPost<DueResponse>('/api/admin/dues', {
      customer_id: customerId,
      invoice_number: form.invoice_number || null,
      reference: form.reference || null,
      amount: form.amount,
      due_date: form.due_date || null,
      notes: form.notes || null,
      penalty_rate: toNumber(form.penalty_rate),
    })

    // Every failure path resets the button. `apiPost` has already shown a toast.
    if (!res.ok) {
      setErr(res.error)
      setSaving(false)
      return
    }

    toast.success(t('dueAdded').en)
    setOpen(false)
    setForm(emptyForm)
    setSaving(false)
    router.refresh()
  }

  return (
    <>
      <Button
        onClick={() => {
          setForm(emptyForm)
          setErr(null)
          setOpen(true)
        }}
      >
        <Plus />
        <Bi k="addDue" />
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogTitle className="text-lg font-semibold">
            <Bi k="addDue" />
          </DialogTitle>

          <FormField labelKey="amount" htmlFor="due-amount" required error={err}>
            <div className="relative">
              <span
                aria-hidden="true"
                className="pointer-events-none absolute top-1/2 left-4 -translate-y-1/2 text-2xl font-bold text-muted-foreground"
              >
                ₹
              </span>
              <Input
                id="due-amount"
                type="text"
                inputMode="decimal"
                enterKeyHint="done"
                autoComplete="off"
                placeholder="0"
                value={form.amount}
                onChange={e => field('amount', e.target.value.replace(/[^\d.]/g, ''))}
                className="tabular h-16 pl-11 text-3xl font-bold md:h-16"
              />
            </div>
          </FormField>

          <FormField labelKey="dueDate" htmlFor="due-date">
            <Input
              id="due-date"
              type="date"
              value={form.due_date}
              onChange={e => field('due_date', e.target.value)}
            />
          </FormField>

          <FormField labelKey="penaltyRatePerMonth" htmlFor="due-penalty">
            <Input
              id="due-penalty"
              type="text"
              inputMode="decimal"
              enterKeyHint="done"
              placeholder="0"
              value={form.penalty_rate}
              onChange={e => field('penalty_rate', e.target.value.replace(/[^\d.]/g, ''))}
            />
          </FormField>

          <FormField labelKey="invoiceNumber" htmlFor="due-invoice">
            <Input
              id="due-invoice"
              placeholder={t('autoGeneratedIfBlank').en}
              value={form.invoice_number}
              onChange={e => field('invoice_number', e.target.value)}
            />
          </FormField>

          <FormField labelKey="reference" htmlFor="due-reference">
            <Input
              id="due-reference"
              value={form.reference}
              onChange={e => field('reference', e.target.value)}
            />
          </FormField>

          <FormField labelKey="notesOptional" htmlFor="due-notes">
            <Input
              id="due-notes"
              enterKeyHint="done"
              value={form.notes}
              onChange={e => field('notes', e.target.value)}
            />
          </FormField>

          <ActionButton
            size="lg"
            icon={Plus}
            labelKey="addDue"
            loading={saving}
            onClick={save}
            className="shrink-0 md:w-full"
          />
        </DialogContent>
      </Dialog>
    </>
  )
}
